In [1]:
import numpy as np
import pandas as pd

import pyarrow as pa

import os

In [2]:
import pyarrow.dataset as ds

In [3]:
dataset = ds.dataset("s3://ursa-labs-taxi-data/2019/")

In [4]:
dataset.files

['ursa-labs-taxi-data/2019/01/data.parquet',
 'ursa-labs-taxi-data/2019/02/data.parquet',
 'ursa-labs-taxi-data/2019/03/data.parquet',
 'ursa-labs-taxi-data/2019/04/data.parquet',
 'ursa-labs-taxi-data/2019/05/data.parquet',
 'ursa-labs-taxi-data/2019/06/data.parquet']

In [5]:
dataset.schema

vendor_id: string
pickup_at: timestamp[us]
dropoff_at: timestamp[us]
passenger_count: int8
trip_distance: float
rate_code_id: string
store_and_fwd_flag: string
pickup_location_id: int32
dropoff_location_id: int32
payment_type: string
fare_amount: float
extra: float
mta_tax: float
tip_amount: float
tolls_amount: float
improvement_surcharge: float
total_amount: float
congestion_surcharge: float
-- schema metadata --
pandas: '{"index_columns": [{"kind": "range", "name": null, "start": 0, "' + 2548

In [6]:
import pyarrow.compute as pc

In [7]:
col_sum = 0
count = 0
i = 0
for batch in dataset.to_batches(columns=["fare_amount"]):
    col_sum += pc.sum(batch.column("fare_amount")).as_py()
    count += batch.num_rows
    print("Batch ", i)
    i += 1

col_sum / count

Batch  0
Batch  1
Batch  2
Batch  3
Batch  4
Batch  5
Batch  6
Batch  7
Batch  8
Batch  9
Batch  10
Batch  11
Batch  12
Batch  13
Batch  14
Batch  15
Batch  16
Batch  17
Batch  18
Batch  19
Batch  20
Batch  21
Batch  22
Batch  23
Batch  24
Batch  25
Batch  26
Batch  27
Batch  28
Batch  29
Batch  30
Batch  31
Batch  32
Batch  33
Batch  34
Batch  35
Batch  36
Batch  37
Batch  38
Batch  39
Batch  40
Batch  41
Batch  42
Batch  43
Batch  44
Batch  45
Batch  46
Batch  47
Batch  48
Batch  49
Batch  50
Batch  51
Batch  52
Batch  53
Batch  54
Batch  55
Batch  56
Batch  57
Batch  58
Batch  59
Batch  60
Batch  61
Batch  62
Batch  63
Batch  64
Batch  65
Batch  66
Batch  67
Batch  68
Batch  69
Batch  70
Batch  71
Batch  72
Batch  73
Batch  74
Batch  75
Batch  76
Batch  77
Batch  78
Batch  79
Batch  80
Batch  81
Batch  82
Batch  83
Batch  84
Batch  85
Batch  86
Batch  87
Batch  88
Batch  89
Batch  90
Batch  91
Batch  92
Batch  93
Batch  94
Batch  95
Batch  96
Batch  97
Batch  98
Batch  99
Batch  100
Batch  101
Batch  102
Batch  103
Batch  104
Batch  105
Batch  106
Batch  107
Batch  108
Batch  109
Batch  110
Batch  111
Batch  112
Batch  113
Batch  114
Batch  115
Batch  116
Batch  117
Batch  118
Batch  119
Batch  120
Batch  121
Batch  122
Batch  123
Batch  124
Batch  125
Batch  126
Batch  127
Batch  128
Batch  129
Batch  130
Batch  131
Batch  132
Batch  133
Batch  134
Batch  135
Batch  136
Batch  137
Batch  138
Batch  139
Batch  140
Batch  141
Batch  142
Batch  143
Batch  144
Batch  145
Batch  146
Batch  147
Batch  148
Batch  149
Batch  150
Batch  151
Batch  152
Batch  153
Batch  154
Batch  155
Batch  156
Batch  157
Batch  158
Batch  159
Batch  160
Batch  161
Batch  162
Batch  163
Batch  164
Batch  165
Batch  166
Batch  167
Batch  168
Batch  169
Batch  170
Batch  171
Batch  172
Batch  173
Batch  174
Batch  175
Batch  176
Batch  177
Batch  178
Batch  179
Batch  180
Batch  181
Batch  182
Batch  183
Batch  184
Batch  185
Batch  186
Batch  187
Batch  188
Batch  189
Batch  190
Batch  191
Batch  192
Batch  193
Batch  194
Batch  195
Batch  196
Batch  197
Batch  198
Batch  199
Batch  200
Batch  201
Batch  202
Batch  203
Batch  204
Batch  205
Batch  206
Batch  207
Batch  208
Batch  209
Batch  210
Batch  211
Batch  212
Batch  213
Batch  214
Batch  215
Batch  216
Batch  217
Batch  218
Batch  219
Batch  220
Batch  221
Batch  222
Batch  223
Batch  224
Batch  225
Batch  226
Batch  227
Batch  228
Batch  229
Batch  230
Batch  231
Batch  232
Batch  233
Batch  234
Batch  235
Batch  236
Batch  237
Batch  238
Batch  239
Batch  240
Batch  241
Batch  242
Batch  243
Batch  244
Batch  245
Batch  246
Batch  247
Batch  248
Batch  249
Batch  250
Batch  251
Batch  252
Batch  253
Batch  254
Batch  255
Batch  256
Batch  257
Batch  258
Batch  259
Batch  260
Batch  261
Batch  262
Batch  263
Batch  264
Batch  265
Batch  266
Batch  267
Batch  268
Batch  269
Batch  270
Batch  271
Batch  272
Batch  273
Batch  274
Batch  275
Batch  276
Batch  277
Batch  278
Batch  279
Batch  280
Batch  281
Batch  282
Batch  283
Batch  284
Batch  285
Batch  286
Batch  287
Batch  288
Batch  289
Batch  290
Batch  291
Batch  292
Batch  293
Batch  294
Batch  295
Batch  296
Batch  297
Batch  298
Batch  299
Batch  300
Batch  301
Batch  302
Batch  303
Batch  304
Batch  305
Batch  306
Batch  307
Batch  308
Batch  309
Batch  310
Batch  311
Batch  312
Batch  313
Batch  314
Batch  315
Batch  316
Batch  317
Batch  318
Batch  319
Batch  320
Batch  321
Batch  322
Batch  323
Batch  324
Batch  325
Batch  326
Batch  327
Batch  328
Batch  329
Batch  330
Batch  331
Batch  332
Batch  333
Batch  334
Batch  335
Batch  336
Batch  337
Batch  338
Batch  339
Batch  340
Batch  341
Batch  342
Batch  343
Batch  344
Batch  345
Batch  346
Batch  347
Batch  348
Batch  349
Batch  350
Batch  351
Batch  352
Batch  353
Batch  354
Batch  355
Batch  356
Batch  357
Batch  358
Batch  359
Batch  360
Batch  361
Batch  362
Batch  363
Batch  364
Batch  365
Batch  366
Batch  367
Batch  368
Batch  369
Batch  370
Batch  371
Batch  372
Batch  373
Batch  374
Batch  375
Batch  376
Batch  377
Batch  378
Batch  379
Batch  380
Batch  381
Batch  382
Batch  383
Batch  384
Batch  385
Batch  386
Batch  387
Batch  388
Batch  389
Batch  390
Batch  391
Batch  392
Batch  393
Batch  394
Batch  395
Batch  396
Batch  397
Batch  398
Batch  399
Batch  400
Batch  401
Batch  402
Batch  403
Batch  404
Batch  405
Batch  406
Batch  407
Batch  408
Batch  409
Batch  410
Batch  411
Batch  412
Batch  413
Batch  414
Batch  415
Batch  416
Batch  417
Batch  418
Batch  419
Batch  420
Batch  421
Batch  422
Batch  423
Batch  424
Batch  425
Batch  426
Batch  427
Batch  428
Batch  429
Batch  430
Batch  431
Batch  432
Batch  433
Batch  434
Batch  435
Batch  436
Batch  437
Batch  438
Batch  439
Batch  440
Batch  441
Batch  442
Batch  443
Batch  444
Batch  445
Batch  446
Batch  447
Batch  448
Batch  449
Batch  450
Batch  451
Batch  452
Batch  453
Batch  454
Batch  455
Batch  456
Batch  457
Batch  458
Batch  459
Batch  460
Batch  461
Batch  462
Batch  463
Batch  464
Batch  465
Batch  466
Batch  467
Batch  468
Batch  469
Batch  470
Batch  471
Batch  472
Batch  473
Batch  474
Batch  475
Batch  476
Batch  477
Batch  478
Batch  479
Batch  480
Batch  481
Batch  482
Batch  483
Batch  484
Batch  485
Batch  486
Batch  487
Batch  488
Batch  489
Batch  490
Batch  491
Batch  492
Batch  493
Batch  494
Batch  495
Batch  496
Batch  497
Batch  498
Batch  499
Batch  500
Batch  501
Batch  502
Batch  503
Batch  504
Batch  505
Batch  506
Batch  507
Batch  508
Batch  509
Batch  510
Batch  511
Batch  512
Batch  513
Batch  514
Batch  515
Batch  516
Batch  517
Batch  518
Batch  519
Batch  520
Batch  521
Batch  522
Batch  523
Batch  524
Batch  525
Batch  526
Batch  527
Batch  528
Batch  529
Batch  530
Batch  531
Batch  532
Batch  533
Batch  534
Batch  535
Batch  536
Batch  537
Batch  538
Batch  539
Batch  540
Batch  541
Batch  542
Batch  543
Batch  544
Batch  545
Batch  546
Batch  547
Batch  548
Batch  549
Batch  550
Batch  551
Batch  552
Batch  553
Batch  554
Batch  555
Batch  556
Batch  557
Batch  558
Batch  559
Batch  560
Batch  561
Batch  562
Batch  563
Batch  564
Batch  565
Batch  566
Batch  567
Batch  568
Batch  569
Batch  570
Batch  571
Batch  572
Batch  573
Batch  574
Batch  575
Batch  576
Batch  577
Batch  578
Batch  579
Batch  580
Batch  581
Batch  582
Batch  583
Batch  584
Batch  585
Batch  586
Batch  587
Batch  588
Batch  589
Batch  590
Batch  591
Batch  592
Batch  593
Batch  594
Batch  595
Batch  596
Batch  597
Batch  598
Batch  599
Batch  600
Batch  601
Batch  602
Batch  603
Batch  604
Batch  605
Batch  606
Batch  607
Batch  608
Batch  609
Batch  610
Batch  611
Batch  612
Batch  613
Batch  614
Batch  615
Batch  616
Batch  617
Batch  618
Batch  619
Batch  620
Batch  621
Batch  622
Batch  623
Batch  624
Batch  625
Batch  626
Batch  627
Batch  628
Batch  629
Batch  630
Batch  631
Batch  632
Batch  633
Batch  634
Batch  635
Batch  636
Batch  637
Batch  638
Batch  639
Batch  640
Batch  641
Batch  642
Batch  643
Batch  644
Batch  645
Batch  646
Batch  647
Batch  648
Batch  649
Batch  650
Batch  651
Batch  652
Batch  653
Batch  654
Batch  655
Batch  656
Batch  657
Batch  658
Batch  659
Batch  660
Batch  661
Batch  662
Batch  663
Batch  664
Batch  665
Batch  666
Batch  667
Batch  668
Batch  669
Batch  670
Batch  671
Batch  672
Batch  673
Batch  674
Batch  675
Batch  676
Batch  677
Batch  678
Batch  679
Batch  680
Batch  681

13.101317234329155

In [8]:
dataset.to_table(filter = ds.field("fare_amount") > 100).to_pandas()

,vendor_id,pickup_at,dropoff_at,passenger_count,trip_distance,rate_code_id,store_and_fwd_flag,pickup_location_id,dropoff_location_id,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,2,2019-01-01 00:23:11,2019-01-01 00:23:25,1,0.340000,5,N,265,265,1,160.0,0.0,0.0,25.000000,0.000000,0.3,185.300003,NaN
1,2,2019-01-01 00:38:36,2019-01-01 01:21:33,2,33.189999,5,N,107,265,1,121.0,0.0,0.0,0.080000,10.500000,0.3,131.880005,NaN
2,1,2019-01-01 00:13:17,2019-01-01 01:06:13,1,44.099998,5,N,132,265,2,150.0,0.0,0.0,0.000000,0.000000,0.3,150.300003,NaN
3,2,2018-12-31 23:59:57,2019-01-01 00:00:00,4,0.000000,5,N,264,265,1,121.0,0.0,0.5,36.540001,0.000000,0.3,158.339996,NaN
4,2,2019-01-01 00:22:44,2019-01-01 00:22:50,1,0.970000,5,N,265,265,1,120.0,0.0,0.5,30.200001,0.000000,0.3,151.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34175,2,2019-06-30 23:36:46,2019-07-01 00:26:50,2,36.959999,5,N,132,265,1,158.0,0.0,0.0,34.980000,16.620001,0.3,209.899994,0.0
34176,2,2019-06-30 23:21:49,2019-06-30 23:21:52,1,0.000000,5,N,265,265,1,160.0,0.0,0.5,15.000000,0.000000,0.3,175.800003,0.0
34177,1,2019-06-30 23:52:45,2019-07-01 00:44:31,1,22.900000,5,N,132,265,1,110.0,0.0,0.0,24.150000,10.500000,0.3,144.949997,0.0
34178,1,2019-06-30 23:03:07,2019-07-01 00:02:03,3,47.799999,5,N,138,265,1,225.0,0.0,0.0,0.000000,16.620001,0.3,241.919998,0.0
34179,2,2019-06-30 23:15:52,2019-06-30 23:45:22,2,23.219999,4,N,132,265,2,101.5,0.5,0.5,0.000000,0.000000,0.3,102.800003,0.0